In [1]:
#1
import numpy as np

In [3]:
#2 
oneD_array= np.arange(1,11)
print(oneD_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# 2d array
twoD_array =np.arange(1,10).reshape(3,3)
print(twoD_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# A numpy array from the list
empty_list=[]
for i in range(10,51,10):
    empty_list.append(i)
empty_list

[10, 20, 30, 40, 50]

In [13]:
# print of each array
print(oneD_array)
print(twoD_array)

#shape of each array
print(oneD_array.shape)
print(twoD_array.shape)

# data type of each array
print(oneD_array.dtype)
print(twoD_array.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(10,)
(3, 3)
int64
int64
