# Numpy


#### Numpy is a fundamental packeges for scientific computing in python. it is a python library that provides multi dimenstional array object and various derived obj such as Masked arrays or Matrics and an assotment of routines for fast operation on arrays including mathematical logigcal ,shape manipluction,sorting selecting,i/o,descrete forurier trasform,basic liner algebra,statical operation ,random simulation,etc.

In [2]:
## Why Numpy ?
## Data Types in python ---> list , dictionary --.slow
### syntex --.python -->easy
## we needed speed and less memory to work  with the huge amount of data.

### numpy --> c languages -->warped --> py


### Why Use NumPy?
#### In Python we have lists that serve the purpose of arrays, but they are slow to process.

#### NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

#### The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

#### Arrays are very frequently used in data science, where speed and resources are very important.

In [3]:
#!pip install numpy

In [4]:
import numpy as np


In [5]:
numpy_array = np.array([1,2,3,4,5])

In [6]:
numpy_array.ndim

1

In [7]:
print(numpy_array.dtype)

int64


In [8]:
twoDarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [9]:
type(twoDarray)

numpy.ndarray

In [10]:
twoDarray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
twoDarray.ndim

3

In [12]:
threedarray = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [13]:
threedarray.ndim

2

In [14]:
threedarray


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
threeDarray =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [16]:
threeDarray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [17]:
# np.array --> multidimensional array

np.array([1,2,3,4,5],dtype = np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [18]:
np.array([3,4,5,67,8],dtype = np.int64) 

array([ 3,  4,  5, 67,  8])

In [19]:
np.array([1,2,3,4,5],dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [20]:
np.array([1,2,3,4,5],dtype = np.bool)

array([ True,  True,  True,  True,  True])

In [21]:
# range function in numpy for i in range(10):

empty_list=[]
for i in range(10):
    empty_list.append(i)
empty_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ab=np.arange(1,17)

In [24]:
ab.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
ab.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [26]:
ab.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [27]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# zeros()
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
# random()
np.random.random((3,4))

array([[0.8240725 , 0.33299681, 0.57485608, 0.73910256],
       [0.08596243, 0.07127608, 0.73505284, 0.94262875],
       [0.71107196, 0.94140789, 0.3051451 , 0.61383448]])

In [31]:
# linspace()
# linspace() function returns evenly spaced numbers over a specified interval. It is similar to the arange() function, but instead of specifying the step size, you specify the number of samples to generate.  
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [34]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [35]:
arr = np.array([1, 2, 3, 4])
# get the first element from the array
print(arr[0])

# get the last element from the array
print(arr[-1])

# get the second element from the array
print(arr[1])

# get the third element from the array
print(arr[2])   

1
4
2
3


In [36]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# Access the element on the first row, second column:
print(arr[0, 1])    

#access the element on the second row
print(arr[1, 2])


2
8


In [37]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#access the third element of the first array of the second array:
print(arr)
print(arr[1, 0, 2])



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
9


In [38]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr[1, 1, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


In [39]:
# 3d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(arr)
print(arr[2, 1, 2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
18


## NumPy Array Slicing
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [41]:
# slice elements from index 4 to end of the array
print(arr[4:])

[5 6 7]


In [42]:
# slice element from the beginning to index 4 (not included)
print(arr[:4])

[1 2 3 4]


### Negative Slicing
Use the minus operator to refer to an index from the end:

In [43]:
print(arr[-4:-1])

[4 5 6]


### Step
use the step other element from index 1 to 5:


In [44]:
print(arr[1:5:2])

[2 4]


In [45]:
# return every other element fromthe array
print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [46]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [47]:
# from both elements return index2 

print(arr[0:2,2])

[3 8]


In [48]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### vector,Matrix and, Tensor


In [49]:
vector =np.array([1,2,3,4,5])
print("vector:", vector)

matrix = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("matrix:", matrix)

tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("tensor:", tensor)

vector: [1 2 3 4 5]
matrix: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### array reshaping

In [50]:
arr =np.arange(12)
print(arr)

reshaped_arr = arr.reshape(3,4)
print(reshaped_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
#ravel() function returns a flattened one-dimensional array. It is similar to the flatten() function, but it returns a view of the original array whenever possible. This means that modifying the raveled array will also modify the original array, and vice versa. If you want a copy of the original array, you can use the flatten() function instead.
ravelled_arr = reshaped_arr.ravel()
print(ravelled_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
# transpose() function returns a view of the original array with its axes transposed. This means that the rows become columns and the columns become rows. The transpose() function does not modify the original array, but instead returns a new array with the transposed shape.
transposed_arr = reshaped_arr.transpose()
print(transposed_arr)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### operations on numpy array

In [55]:
# slicing and indexing in numpy
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0, 1])    # Access the element on the first row, second column
print(arr[1, 2])    # Access the element on the second row, third column
print(arr[1, 1:4])  # Access a slice of the second row, from index 1 to index 4 (not included)
print(arr[0:2, 2])  # Access a slice of both rows, at index 2
print(arr[0:2, 1:4])  # Access a slice of both rows, from index 1 to index 4 (not included) 


2
8
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [56]:
arr_2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
print(arr_2d[1, 1])    # Access the element on the second row, second column    
print(arr_2d[0:2, 1:3])  # Access a slice of the first two rows, from index 1 to index 3 (not included)
print(arr_2d[0:3, 0:2])  # Access a slice of the first three rows, from index 0 to index 2 (not included)
print(arr_2d[0:3, 0:2])  # Access a slice of the first three rows, from index 0 to index 2 (not included)
print(arr_2d[0:3, 0:2])  # Access a slice of the first three rows, from index 0 to index 2 (not included)
print(arr_2d[2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[[2 3]
 [5 6]]
[[1 2]
 [4 5]
 [7 8]]
[[1 2]
 [4 5]
 [7 8]]
[[1 2]
 [4 5]
 [7 8]]
[7 8 9]


### sorting


In [57]:
unsorted_arr = np.array([3, 1, 4, 2, 5])
# Sort the array in ascending order
sorted_arr = np.sort(unsorted_arr)
print("Unsorted array:", unsorted_arr)
print("Sorted array:", sorted_arr)

Unsorted array: [3 1 4 2 5]
Sorted array: [1 2 3 4 5]


In [60]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Sort the array along the first axis (rows)
sorted_arr_2d = np.sort(arr_2d, axis=0)
print("Original 2D array:\n", arr_2d)
print("Sorted 2D array along the first axis (rows):\n", sorted_arr_2d)

Original 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Sorted 2D array along the first axis (rows):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### filter

In [61]:
numbers =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10]


### filter with mask

In [62]:
mask =numbers > 5   
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [66]:
indices =[0, 2, 4, 6, 8]
print("Elements at indices", indices, ":", numbers[indices])

where_mask = np.where(numbers > 5)
print(where_mask)
print("Indices of elements greater than 5:", numbers[where_mask[0]])

Elements at indices [0, 2, 4, 6, 8] : [1 3 5 7 9]
(array([5, 6, 7, 8, 9]),)
Indices of elements greater than 5: [ 6  7  8  9 10]


In [67]:
condition = (numbers > 5) & (numbers < 9)
print("Numbers greater than 5 and less than 9:", numbers[condition])

Numbers greater than 5 and less than 9: [6 7 8]


In [68]:
condition_array =np.where((numbers > 5) & (numbers < 9))
print("Indices of elements greater than 5:", condition_array[0])


Indices of elements greater than 5: [5 6 7]


In [69]:
condition = np.where(numbers > 5, "True ", "False")
print(condition)

['False' 'False' 'False' 'False' 'False' 'True ' 'True ' 'True ' 'True '
 'True ']


### Adding and removing data

In [70]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Element-wise addition
result_add = arr1 + arr2
print("Element-wise addition:", result_add) 

combined = np.concatenate((arr1, arr2))
print("Concatenated array:", combined)



Element-wise addition: [5 7 9]
Concatenated array: [1 2 3 4 5 6]


In [71]:
# Array campatibility and broadcasting  
a =np.array([1,2,3])
b =np.array([4,5,6])
c =np.array([7,8,9])

print("campatibilty shape",a.shape == b.shape == c.shape)



campatibilty shape True


In [72]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
# Reshape the array to a different shape
new_row =np.array([[7, 8, 9]])
reshaped_array = np.vstack((original_array, new_row))
print("Reshaped array:\n", reshaped_array)

Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
new_column = np.array([[10], [11], [12]])
reshaped_array_with_column = np.hstack((reshaped_array, new_column))
print("Reshaped array with new column:\n", reshaped_array_with_column)  

Reshaped array with new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
